fix

diff --git a/templates/cann.Dockerfile.j2 b/templates/cann.Dockerfile.j2
--- a/templates/cann.Dockerfile.j2
+++ b/templates/cann.Dockerfile.j2
@@ -12,25 +12,26 @@ ARG CANN_CHIP={{ item.cann_chip }}
 ARG CANN_VERSION={{ item.cann_version }}
 ARG BASE_URL=https://ascend-repo.obs.cn-east-2.myhuaweicloud.com
 
-# Set environment variables
-
-# NOTE: kernels are arch-specific after 8.0.RC3.alpha002
-RUN if [ "${TARGETPLATFORM}" = "linux/amd64" ] ; then \
-        ARCH="x86_64" \
+RUN if [ "${TARGETPLATFORM}" = "linux/amd64" ]; then \
+        ARCH="x86_64"; \
     else \
-        ARCH="aarch64" \
+        ARCH="aarch64"; \
     fi && \
     # NOTE: kernels are arch-specific after 8.0.RC3.alpha002
-    if [ "${CANN_VERSION}" = "8.0.0" ] || [ "${CANN_VERSION}" = "8.0.RC3" ]; then \
-        KERNELS_ARCH="linux-${ARCH}" \
+    if [ "${CANN_VERSION}" = "8.0.0"  ||  "${CANN_VERSION}" = "8.0.RC3" ]; then \
+        KERNELS_ARCH="linux-${ARCH}"; \
     else \
-        KERNELS_ARCH="linux" \
+        KERNELS_ARCH="linux"; \
     fi && \
     TOOLKIT_FILE="Ascend-cann-toolkit_${CANN_VERSION}_linux-${ARCH}.run" && \
     KERNELS_FILE="Ascend-cann-kernels-${CANN_CHIP}_${CANN_VERSION}_${KERNELS_ARCH}.run" && \
     NNAL_FILE="Ascend-cann-nnal_${CANN_VERSION}_linux-${ARCH}.run" && \
-    # NOTE: Different CANN VERSION has different Download url
-    if [[ "${CANN_VERSION}" == *"alpha"* ]]; then \
+    echo "${TOOLKIT_FILE}" > /tmp/toolkit_file.txt && \
+    echo "${KERNELS_FILE}" > /tmp/kernels_file.txt && \
+    echo "${NNAL_FILE}" > /tmp/nnal_file.txt
+
+# NOTE: Different CANN VERSION has different Download url
+RUN if echo "${CANN_VERSION}" | grep -q "alpha"; then \
         if [ "${CANN_VERSION}" = "8.0.RC2.alpha001" ]; then \
             version="V100R001C18B800TP015"; \
         elif [ "${CANN_VERSION}" = "8.0.RC2.alpha002" ]; then \
@@ -40,12 +41,16 @@ RUN if [ "${TARGETPLATFORM}" = "linux/amd64" ] ; then \
         elif [ "${CANN_VERSION}" = "8.0.RC3.alpha002" ]; then \
             version="V100R001C19SPC702"; \
         else \
-            echo "Error: Unsupported CANN_VERSION: ${CANN_VERSION}" && exit 1; \
-        fi && \
-        URL_PREFIX="${BASE_URL}/Milan-ASL/Milan-ASL%20${version}" && \
+            echo "Error: Unsupported CANN_VERSION: ${CANN_VERSION}"; \
+            exit 1; \
+        fi; \
+        URL_PREFIX="${BASE_URL}/Milan-ASL/Milan-ASL%20${version}"; \
     else \
-        URL_PREFIX="${BASE_URL}/CANN/CANN%20${CANN_VERSION}" && \
+        URL_PREFIX="${BASE_URL}/CANN/CANN%20${CANN_VERSION}"; \
     fi && \
+    TOOLKIT_FILE=$(cat /tmp/toolkit_file.txt) && \
+    KERNELS_FILE=$(cat /tmp/kernels_file.txt) && \
+    NNAL_FILE=$(cat /tmp/nnal_file.txt) && \
     CANN_TOOLKIT_URL="${URL_PREFIX}/${TOOLKIT_FILE}" && \
     CANN_KERNELS_URL="${URL_PREFIX}/${KERNELS_FILE}" && \
     CANN_NNAL_URL="${URL_PREFIX}/${NNAL_FILE}" && \
